spring.application.name: sample-ai

springdoc.show-actuator: true

management.endpoints.web.exposure.include: '*'
management:
  endpoint.health:
    show-details: always
    probes:
      enabled: true

spring:
  ai:
    openai:
      base-url: https://llama32-demo.apps.piomin.ewyw.p1.openshiftapps.com
      api-key: dummy
      chat:
        options:
          model: llama32